<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <BaseOutputPath>C:\MyProjects\Ju.GundamWars\Binary</BaseOutputPath>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Versionings\**" />
    <Compile Remove="_\**" />
    <EmbeddedResource Remove="Versionings\**" />
    <EmbeddedResource Remove="_\**" />
    <None Remove="Versionings\**" />
    <None Remove="_\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.BizConst\Ju.GundamWars.BizConst.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Core\Ju.GundamWars.Core.csproj" />
  </ItemGroup>

</Project>
