<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows7.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <AssemblyName>JuGundamWars</AssemblyName>
    <ApplicationIcon>Resources\JuGundamWars.ico</ApplicationIcon>
    <BaseOutputPath>..\..\Binary</BaseOutputPath>
	  <InterceptorsPreviewNamespaces>$(InterceptorsPreviewNamespaces);Microsoft.Extensions.Configuration.Binder.SourceGeneration</InterceptorsPreviewNamespaces>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Resources\JuGundamWars.ico" />
    <None Remove="Resources\SplashScreen.png" />
    <None Remove="SplashScreen.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Resources\JuGundamWars.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignColors" Version="3.1.0" />
    <PackageReference Include="MaterialDesignThemes" Version="5.1.0" />
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="3.1.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="NLog.Extensions.Logging" Version="5.3.11" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.Application\Ju.GundamWars.Application.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Core\Ju.GundamWars.Core.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Persistence2\Ju.GundamWars.Persistence2.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Persistence\Ju.GundamWars.Persistence.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Data\" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Data\JuGundamWars.base.db" Link="Data\JuGundamWars.base.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Data\JuGundamWarsMaster.db" Link="Data\JuGundamWarsMaster.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\JuGundamWars.ico">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Resources\SplashScreen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </SplashScreen>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
