DROP TABLE IF EXISTS [MobileSSkill];
CREATE TABLE [MobileSSkill] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , [SkillId] INTEGER NOT NULL
  , [NameSuffix] TEXT NOT NULL
  , [GradeType] INTEGER NOT NULL
  , [Order] INTEGER NOT NULL
);
