DROP TABLE IF EXISTS [PilotAbility];
CREATE TABLE [PilotAbility] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , [Rank] INTEGER NOT NULL
  , [BoostCategoryType] INTEGER NOT NULL
  , [BoostStatusType] INTEGER NOT NULL
  , [CalcMethodType] INTEGER NOT NULL
  , [Value] INTEGER NOT NULL
  , [Order] INTEGER NOT NULL
);
