DROP TABLE IF EXISTS [SupportSlot];
CREATE TABLE [SupportSlot] (
  [Id] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
  , [SupportSlotKindType] INTEGER NOT NULL
  , [BoostStatusType] INTEGER NOT NULL
  , [CalcMethodType] INTEGER NOT NULL
  , [Value] INTEGER NOT NULL
  , [Order] INTEGER NOT NULL
);
