<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.Client.Const\Ju.GundamWars.Client.Const.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Client.Master\Ju.GundamWars.Client.Master.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Client.Transaction\Ju.GundamWars.Client.Transaction.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Core\Ju.GundamWars.Core.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Server\Ju.GundamWars.Server.csproj" />
  </ItemGroup>

</Project>
