<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commons\UseCase\OutputPort\**" />
    <EmbeddedResource Remove="Commons\UseCase\OutputPort\**" />
    <None Remove="Commons\UseCase\OutputPort\**" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.Core\Ju.GundamWars.Core.csproj" />
  </ItemGroup>

</Project>
