<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <ApplicationIcon>Resources\JuGundamWars.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Commons\ViewModel\**" />
    <Compile Remove="Cuspas\Presentation\**" />
    <EmbeddedResource Remove="Commons\ViewModel\**" />
    <EmbeddedResource Remove="Cuspas\Presentation\**" />
    <None Remove="Commons\ViewModel\**" />
    <None Remove="Cuspas\Presentation\**" />
    <Page Remove="Commons\ViewModel\**" />
    <Page Remove="Cuspas\Presentation\**" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="Resources\JuGundamWars.ico" />
    <None Remove="Resources\SplashScreen.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Resources\JuGundamWars.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MaterialDesignThemes.MahApps" Version="3.1.0" />
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.122" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.Client\Ju.GundamWars.Client.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Mobiles\Presentation\" />
    <Folder Include="Tags\Presentation\" />
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Resources\SplashScreen.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </SplashScreen>
  </ItemGroup>

  <ItemGroup>
    <None Update="MasterUpdateSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="SystemSettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
