<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Cuspas\**" />
    <Compile Remove="Pilots\**" />
    <Compile Remove="Supports\**" />
    <EmbeddedResource Remove="Cuspas\**" />
    <EmbeddedResource Remove="Pilots\**" />
    <EmbeddedResource Remove="Supports\**" />
    <None Remove="Cuspas\**" />
    <None Remove="Pilots\**" />
    <None Remove="Supports\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.7" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Ju.GundamWars.Core\Ju.GundamWars.Core.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Server.Master\Ju.GundamWars.Server.Master.csproj" />
    <ProjectReference Include="..\Ju.GundamWars.Server.Transaction\Ju.GundamWars.Server.Transaction.csproj" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\Data\JuGundamWars.base.db" Link="Data\JuGundamWars.base.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="..\..\Data\JuGundamWarsMaster.db" Link="Data\JuGundamWarsMaster.db">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>
